prezly/theme-kit-js

package-lock.json
package.json
src/data-fetching/api/PrezlyApi.ts
src/data-fetching/api/queries.ts
src/newsroom-context/context.tsx
src/newsroom-context/hooks/index.ts
src/newsroom-context/hooks/useEmbedStory.ts

This is a feature required for Story Bookmark components to work.
See https://linear.app/prezly/issue/MT-4606/react-newsroom-rendering-for-story-bookmarks
Based on code by @aspirisen

Feature: embed stories

---

package.json

Without this config TS watch task clears all the terminal output

Fix watch task

---

package-lock.json
package.json

Drop unused @prezly/slate-types dependency

---

package-lock.json
package.json
src/adapter-nextjs/index.ts
src/adapter-nextjs/page-props/category.ts
src/adapter-nextjs/page-props/gallery.ts
src/adapter-nextjs/page-props/galleryAlbum.ts
src/adapter-nextjs/page-props/home.ts
src/adapter-nextjs/page-props/index.ts
src/adapter-nextjs/page-props/lib/types.ts
src/adapter-nextjs/page-props/story.ts
src/adapter-nextjs/page-props/storyPreview.ts
src/data-fetching/constants.ts

TODO: Add documentation on the helper methods.
The code is basically taken from the Bea theme, with some wrapping logic to allow for passing custom options.

[TF-750] Move prop fetching logic for pages into the Theme Kit

---

package-lock.json
package.json
src/data-fetching/boilerplate.ts
src/data-fetching/getDataRequestLink.ts
src/data-fetching/index.ts
src/data-fetching/isEmbargoStory.ts

This PR is about moving some utility functions that are not theme specific into the Theme Kit.

[TF-799] move generic utility functions to theme kit

---

.eslintignore
package-lock.json
package.json
src/__mocks__/languages.ts
src/__mocks__/story.ts
src/intl/languages.test.ts
src/intl/languages.ts
src/intl/locale.test.ts
src/intl/locale.ts
src/intl/localeObject.test.ts
src/intl/localeObject.ts
tsconfig.json

Also fixed a couple small bugs on the way. Will make a preview version to test that it didn't break anything else.

[TF-621] Add unit tests to locale logic

---

package-lock.json
package.json
src/__mocks__/languages.ts
src/adapter-nextjs/page-props/home.ts
src/adapter-nextjs/page-props/sitemap/getServerSideProps.ts
src/adapter-nextjs/page-props/story.ts
src/data-fetching/api/PrezlyApi.ts
src/data-fetching/api/queries.ts

Depends on this: :heavy_check_mark: https://github.com/prezly/javascript-sdk/pull/186

[DEV-9503] Add opt-in support for pinned stories

---

src/components-nextjs/PageSeo/PageSeo.tsx

Forgot to push my changes...
see https://github.com/prezly/theme-kit-nextjs/pull/176/files#r1048461480

Fix meta tags filtering for null

---

src/utils/boilerplate.ts

https://linear.app/prezly/issue/QRF-865/[theme]-website-information-issues-with-showing-website-info

[QRF-865] boilerplate - added website check to `hasAnyContactInformation`

---

lerna.json
package-lock.json
packages/core/package.json
packages/core/src/data-fetching/api/PrezlyApi.ts
packages/core/src/data-fetching/api/queries.ts
packages/nextjs/package.json
packages/nextjs/src/adapter-nextjs/api-handlers/fetchStories.ts
packages/nextjs/src/adapter-nextjs/page-props/home.ts
packages/nextjs/src/infinite-loading/useInfiniteStoriesLoading.ts

CARE-1415
This is needed for a customer request to filter out stories from a particular category from the home page.

[CARE-1415] Allow additional query filtering for stories

---

lerna.json
package-lock.json
package.json
packages/core/package.json
packages/core/src/data-fetching/api/PrezlyApi.ts
packages/nextjs/package.json
packages/nextjs/src/playwright/config.ts
packages/nextjs/src/playwright/index.ts

- Also added `isomorphic-fetch` polyfill to ensure `PrezlyApi` working in all environments.

[CARE-1535] Export shared Playwright config for themes

---

.github/workflows/test.yml
.github/workflows/typecheck.yml
lerna.json
package-lock.json
package.json
packages/core/package.json
packages/core/src/data-fetching/api/PrezlyApi.ts
packages/nextjs/package.json

- bumped minimum SDK version to 16
- specified V4 format when fetching a single story

[DEV-10948] Fetch stories in V4 format, bump SDK version

---

packages/nextjs/src/adapter-nextjs/api-handlers/fetchStories.ts
packages/nextjs/src/infinite-loading/useInfiniteStoriesLoading.ts

Followup on https://github.com/prezly/theme-nextjs-sony/pull/16#discussion_r1230799992

[CARE-1825] Expose `storiesTotal` in `fetchStories` of next.js adapter

---

lerna.json
package-lock.json
packages/core/src/utils/index.ts
packages/core/src/utils/isGalleryEmpty.ts
packages/nextjs/package.json
packages/nextjs/src/adapter-nextjs/page-props/galleryAlbum.ts

See [CARE-2009](https://linear.app/prezly/issue/CARE-2009/sony-video-galleries-giving-404).

[CARE-2009] Fixed video galleries being treated as "not found" due to not having any images

---

package-lock.json
packages/core/package.json
packages/core/src/environment.ts
packages/core/src/index.ts
packages/nextjs/package.json
packages/nextjs/src/adapters/environment/server.ts

- Move env helper to the `core` package
- Cleanup unused dependencies

[DEV-11957] Next.js 13 - Move env helper to the `core` package

---

package-lock.json
packages/ui/src/components/Boilerplate/Boilerplate.tsx
packages/ui/src/components/Button/Button.tsx
packages/ui/src/components/Button/ButtonLink.tsx
packages/ui/src/components/Button/Icon.tsx
packages/ui/src/components/Dropdown/Dropdown.tsx
packages/ui/src/components/GalleryMedia/GalleryMedia.tsx
packages/ui/src/components/Hero/Hero.tsx
packages/ui/src/components/Hero/components/HeroImage/HeroImage.tsx
packages/ui/src/components/Link/Link.tsx
packages/ui/src/components/Navigation/Navigation.stories.tsx
packages/ui/src/components/Navigation/Navigation.tsx
packages/ui/src/components/Navigation/components/CategoriesDropdown.tsx
packages/ui/src/components/Navigation/components/LanguagesDropdown.tsx
packages/ui/src/components/Navigation/types.ts
packages/ui/src/components/StoryCard/StoryCard.tsx
packages/ui/src/components/StoryCard/components/StoryImage/StoryImage.tsx
packages/ui/src/components/StoryShareLinks/ShareButton.tsx
packages/ui/src/components/StoryShareLinks/StoryShareLinks.tsx
packages/ui/src/components/SubscriptionCta/SubscriptionCta.tsx

Storybook link: https://6530e13a6911737a3a258bcc-ovdfnvvgnt.chromatic.com/

[DEV-11962] Storybook components QA

---

packages/core/src/content-delivery/ContentDelivery.ts
packages/core/src/content-delivery/index.ts
packages/core/src/index.ts

- Also, extract `include` into separate options object parameters
- Provide interfaces for stories-related search methods parameters

[DEV-12007] Next.js 13 - Make `allStories()` support `include` too

---

lerna.json
package-lock.json
packages/core/package.json
packages/core/src/intl/languages.ts
packages/intl/package.json
packages/nextjs/package.json
packages/ui/package.json

I figured that we shouldn't invest in a more complex setup for a one-off custom theme feature. This logic will also likely heavily change with next major Theme Kit version, so I went with this simple (albeit a bit hacky) approach.

[CARE-3532] Allow bypassing locale code shortening in URLs

---

packages/core/src/content-delivery/ContentDelivery.ts
packages/core/src/content-delivery/cache/memory.ts
packages/core/src/content-delivery/cache/stacked.ts
packages/core/src/content-delivery/cache/type.ts
packages/nextjs/src/adapters/prezly/cache/redis.ts

- Namespace data per newsroom/theme/formats setting
- Only cache network-dependent methods

[DEV-12072] Experiment - Fix/Improve Redis cache for API data

---

.github/workflows/chromatic.yml
package-lock.json
packages/ui/.storybook/main.js
packages/ui/package.json

So it turned out it was necessary to install `vite-plugin-turbosnap`.
See:
- https://github.com/IanVS/vite-plugin-turbosnap
- https://github.com/chromaui/chromatic-cli/issues/868

[DEV-12476] Fix -Chromatic check

---

.github/workflows/test.yml
.github/workflows/typecheck.yml
package-lock.json
package.json
packages/core/package.json
packages/nextjs/package.json
packages/ui/package.json
packages/ui/src/components/Navigation/__mocks__/categories.ts

Note: this is patching the previous 7.x version branch

[CARE-4335] Feature - Do not show categories that do not have any published stories

---

packages/intl/i18n/en.json
packages/intl/src/formatting/datetime/lib.test.ts
packages/intl/src/formatting/datetime/lib.ts
packages/intl/src/formatting/datetime/shared.test.ts
packages/intl/src/formatting/messages/lib.test.ts
packages/intl/src/formatting/messages/lib.ts
packages/intl/src/formatting/messages/types.ts
packages/intl/src/messages/content.ts
packages/intl/src/utils/index.ts
packages/intl/src/utils/withCache.ts
packages/nextjs/src/adapters/intl/server.tsx
packages/react/src/intl/BaseFormattedMessage.tsx
packages/react/src/intl/IntlContext.tsx

https://github.com/prezly/theme-kit-js/blob/2289f20e0ea2ee570a8c48dc42c4dad7c3b1810c/packages/intl/i18n/en.json#L80-L82

[DEV-12530] Feature - Intl pluralization support

---

lerna.json
package-lock.json
packages/nextjs/package.json
packages/nextjs/src/adapters/metadata/lib/generateMediaGalleryPageMetadata.ts

- adds `Media gallery: ` prefix to page's title
- adds `No images/videos` or `N image(s)/video(s)` prefix to page's description

[DEV-12530] Feature - Enrich media gallery page title and description

---

.github/workflows/test.yml
.github/workflows/typecheck.yml
package-lock.json
package.json
packages/core/package.json
packages/nextjs/package.json
packages/ui/package.json

https://github.com/prezly/javascript-sdk/releases/tag/v20.0.0

Upgrade @prezly/sdk

---

packages/intl/i18n/en.json
packages/intl/src/messages/content.ts

Added new strings for the homepage filtering, so we can order the translations.

[DEV-12654] Add new strings for homepage filtering

---

lerna.json
package-lock.json
packages/core/package.json
packages/intl/package.json
packages/nextjs/package.json
packages/react/package.json
packages/react/src/intl/BaseFormattedTime.tsx
packages/ui/package.json

I forgot to wrap the UTC offset in parentheses 🙈

Fix - Replace GMT with UTC and then wrap the whole offset in parentheses

---

.github/workflows/test.yml
.github/workflows/typecheck.yml
package-lock.json
package.json
packages/core/package.json
packages/nextjs/package.json
packages/react/package.json
packages/ui/package.json
packages/ui/src/components/ContentRenderer/components/Attachment/Attachment.tsx
packages/ui/src/components/ContentRenderer/components/Gallery.tsx
packages/ui/src/components/ContentRenderer/components/Image.tsx
packages/ui/src/components/ContentRenderer/components/RichText/Link.tsx

Bump the following dependencies to their latest versions:
- @prezly/sdk
- @prezly/content-renderer-react-js
- @prezly/analytics-nextjs

[CARE-4942] Bump @prezly/sdk

---

.github/workflows/test.yml
.github/workflows/typecheck.yml
package-lock.json
package.json
packages/core/package.json
packages/intl/package.json
packages/nextjs/package.json
packages/ui/package.json

- Upgrade @prezly/sdk to the latest version (required for OneTrust integration)

[CARE-4941] Feature - Support OneTrust cookie integration

---

lerna.json
package-lock.json
packages/nextjs/package.json

Required for: https://github.com/prezly/privacy-portal/pull/386

[CARE-4911] Feature - Add support for Next 14 in v5.x

---

packages/intl/i18n/en.json
packages/intl/src/messages/index.ts
packages/intl/src/messages/share.ts

[DEV-21506] Add missing translation strings for the Share block
