README.md

The official name seems to be `Next.js` so I've just changed it here to match that.
Also slightly tweaked our theme names.

Use Next.js name consistently, tweaked our repo names

---

src/data-fetching/index.ts
src/data-fetching/lib/index.ts
src/data-fetching/types.ts

Providing this variable as `PREZLY_MODE="preview"` will disable tracking on all pages.
Please see https://github.com/prezly/theme-nextjs-bea/pull/94 to learn how it's used.

Add PREZLY_MODE env variable

---

package-lock.json
package.json
src/adapter-nextjs/processRequest.ts
src/intl/locale.ts

These changes allow for themes that don't support multi-language to still work with theme-kit.
Previously, if `i18n` section of `next.config.js` was not setup for multi-language support, theme would endlessly redirect to the same locale.
Tested on the Heartbeat theme, where this issue was first discovered.
Also tested on Bea to confirm that regular multi-language behavior is still working as intended

[TITS-5301] Fix next adapter not working for single-language apps

---

src/data-fetching/lib/getEnvVariables.ts

This feature was done mainly because of [this code in the Heartbeat Theme](https://github.com/prezly/theme-nextjs-heartbeat/blob/7a47166c4fa880849e45d080f41042d6f4869e95/pages/%5Bslug%5D.tsx#L41-L46).
The thing is that it'd be nice to use the same `getEnvVariables` method provided by theme-kit to also get any custom env variables specific to the theme (which it does either way, but TS is complaining about type mismatch).
Now I'm not sure whether the type cast added here is better than just doing this in the Heartbeat code:
```ts
const env = getEnvVariables(context.req) as ProcessEnv;
```

Add return type override to `getEnvVariables`

---

src/data-fetching/api/PrezlyApi.ts

I haven't tested it but we use it the exact same way in the [main app](https://github.com/prezly/prezly/pull/11044/files#diff-e61f0a6d9d5c9bad7543c00071937d7349efca379ef603a14e5c45f25458ddabR40) where it works correctly 🙂

[HD-361] Sort categories by order property

---

package-lock.json
package.json
src/__mocks__/languages.ts
src/intl/languages.test.ts
src/intl/languages.ts
src/intl/localeConfig.js
src/intl/localeObject.test.ts

The issue was that `es-419` code was being shortened to `419` (aka the short region code), but it didn't pass the regexp that I previosly set up for checking that locale code conforms to ISO standarts.
I don't think that URLs like `/419/..` would be a good thing anyway, so I updated the code to exclude the `419` shortcode from possible language codes.

[TF-996] Fix issues with `es-419` locale

---

src/data-fetching/api/PrezlyApi.ts

We should show a 404 page for this error code.

[TF-804] Properly handle API Error 410: Gone for Story Preview

---

README.md
package-lock.json
package.json
src/adapter-nextjs/getNewsroomStaticProps.ts
src/adapter-nextjs/index.ts
src/adapter-nextjs/page-props/category.ts
src/adapter-nextjs/page-props/gallery.ts
src/adapter-nextjs/page-props/galleryAlbum.ts
src/adapter-nextjs/page-props/home.ts
src/adapter-nextjs/page-props/index.ts
src/adapter-nextjs/page-props/lib/types.ts
src/adapter-nextjs/page-props/search.ts
src/adapter-nextjs/page-props/story.ts
src/adapter-nextjs/processRequest.ts
src/adapter-nextjs/processStaticRequest.ts
src/data-fetching/api/PrezlyApi.ts

The support is currently limited to single-language newsrooms, since multi-language support is quite tricky to implement and will not fit into the current cycle. This functionality should be enough for our current use-case (the Lifelog theme).
The SSG page props helpers share a lot of code with their SSR counter-parts, but I'm not sure that refactoring should be done in the scope of this PR.

[TF-925] Add experimental SSG support

---

package-lock.json
package.json
src/index.ts
src/sentry/client.ts
src/sentry/common.ts
src/sentry/index.ts
src/sentry/server.ts

Since all of our themes use the same Sentry config, it made sense to put it in the Theme Kit, so that we have a single source of truth for the sample rate, event tags and ignored errors. It will also enable us to auto-apply the config updates the same way we do it with patches.

[TF-1029] Add shared Sentry config

---

package-lock.json
package.json
src/components-nextjs/document.tsx
src/components-nextjs/index.ts
tsconfig.json

This is another optimisation to streamline the common `_document` wrapper for all of our themes.

[TF-1030] Add shared document class

---

package-lock.json
package.json
src/adapter-nextjs/api-handlers/fetchStories.ts
src/adapter-nextjs/page-props/home.ts
src/data-fetching/api/PrezlyApi.ts
src/data-fetching/api/lib.ts
src/infinite-loading/types.ts
src/infinite-loading/useInfiniteLoading.ts
src/infinite-loading/useInfiniteStoriesLoading.ts

The issue that this PR is intended to fix was present on most of our themes from day one, but somehow it was either overlooked or ignored.
For themes having a dedicated "highlighted story" card (either to display latest or pinned story), the card grid does not look even, since the grid for other stories is missing one item that is moved to "highlighted".
With current abstractions, it's quite hard to have separate page sizes for the initial load and subsequent loads performed by infinite loading.
This PR adds `withHighlightedStory` to `getHomepageServerSideProps ` as well as the API methods that it uses. 
It will still use the `pageSize` parameter for infinite loading, but will load one more story for the first page, and also offset all subsequent page loads by 1 to prevent duplicate …

[QRF-673] Add `withHighlightedStory` parameter to properly handle highlighted stories

---

src/sentry/common.ts

We had lots of junk Sentry errors coming from our themes, mostly caused by misbehaving extensions or people mocking about in the DevTools. This config update should address that and clean up our Sentry dashboard big time 🤞🏻 
Here's only a small subset of errors this is intended to clean up. Note that they are all caused by referring to variables from frameworks/libraries, that are not related to our themes in any way.

Add code to ignore junk Sentry error events

---

src/sentry/client.ts
src/sentry/common.ts
src/sentry/server.ts

The previous PR did not catch all of the junk exceptions, so I refactored the code a bit to get rid of undocumented properties and make the checks more robust

Refactor Sentry config event ignore logic, add extra checks

---

lerna.json
package-lock.json
packages/core/package.json
packages/nextjs/package.json
packages/nextjs/src/infinite-loading/lib/index.ts
packages/nextjs/src/infinite-loading/lib/useAsync.ts
packages/nextjs/src/infinite-loading/lib/useSyncedRef.ts
packages/nextjs/src/infinite-loading/useInfiniteLoading.ts

While most of our themes use this package anyway, it doesn't make sense to bring in the whole package in the Theme Kit just for one hook. This saves about 7.4 Kb Gzipped on apps that don't use `@react-hookz/web`.

[CARE-1518] Get rid of `@react-hookz/web` dependency

---

packages/core/src/seo/getAlternateLanguageLinks.ts

The issue was due to `Array.at()` only being supported in Safari 15.4 and upwards.
Updated to use simple array indexing instead

[CARE-1556] Fix issue with `arr.at is undefined` in safari 14 

---

packages/core/src/intl/languages.ts
packages/nextjs/src/intl/languages.ts

Fix for #301 
Prioritize language selection based on a matching combination of neutral code and short region over solely relying on a short region. This is what fixes the issue.
At this point, I'm going crazy with these sequences of PRs.

[CARE-1572] Priotrizing the language with matching **neutral code & short region** over the only **short region**

---

lerna.json
package-lock.json
packages/nextjs/README.md
packages/nextjs/package.json
packages/nextjs/src/adapter-nextjs/processRequest.ts
packages/nextjs/src/config.ts
packages/nextjs/src/config/index.ts

This fixes issue with Next 13 overriding the `Cache-Control` headers set in `next.config.js`.

[DEV-10857] Add correct `Cache-Control` headers to every page server request, export `withPrezlyConfig` helper

---

packages/nextjs/src/adapter-nextjs/page-props/sitemap/getServerSideProps.ts

It's hard to test it locally, but my guts telling me that `req.headers['x-forwarded-proto']` can be `https,http`

[CARE-1846] Fix sitemap URLs to support any possible value

---

lerna.json
package-lock.json
packages/nextjs/package.json
packages/nextjs/src/components-nextjs/PageSeo/PageSeo.tsx

- The `title` / `description` props logic was broken during the SEO settings project, making the SEO settings title to always override the custom props. This made customizing the title through themes impossible.
- To allow for more control over the title, I added a possibility to pass a function to the `title` prop, so that Themes can construct more complex title while still relying on our SEO settings logic.

[CARE-1893] Fix SEO title/description overrides not working, allow more title customization

---

lerna.json
package-lock.json
packages/nextjs/package.json
packages/nextjs/src/components-nextjs/PageSeo/PageSeo.tsx

`basePath` was not provided when generating absolute URLs (canonical and alternate links), so sites that are not running on the root path would have these URLs invalid.

[CARE-2260] Fix - Provide basePath when generating absolute URLs

---

lerna.json
package-lock.json
package.json
packages/core/package.json
packages/nextjs/README.md
packages/nextjs/package.json
packages/nextjs/src/adapter-nextjs/page-props/sitemap/getServerSideProps.ts
packages/nextjs/src/components-nextjs/PageSeo/lib/getAbsoluteUrl.ts
packages/nextjs/src/config.ts
packages/nextjs/src/index.ts
packages/nextjs/src/infinite-loading/useInfiniteGalleriesLoading.ts
packages/nextjs/src/infinite-loading/useInfiniteStoriesLoading.ts
packages/nextjs/src/intl/locale.ts
packages/nextjs/src/utils.ts

This change adds proper support for Next `basePath` setting, and also exports `getResolvedPath` helper to properly resolve URLs with respect to `basePath` configuration.

[CARE-2307] Support Next.js basePath config

---

package-lock.json
packages/core/package.json
packages/core/src/intl/locale.ts

It can already be known from the `intl` package. No need to dupe it (and have desync issues).

[DEV-11804] Deduplicate supported locales list

---

packages/nextjs/package.json
packages/nextjs/src/index.ts

As importing it via the main entry point in Next.js 13 server environment makes the build fail
> ✓ Linting and checking validity of types
>   Collecting page data  ...TypeError: (0 , o.createContext) is not a function

[DEV-11988] Provide a separate entry point for Sentry configs

---

packages/core/src/intl/languages.ts

This is a change required by a custom theme, but should also be useful for future projects. This change allows us to display either a native language name (current default) or use English naming

[CARE-3532] Allow specyfying whether a native name or english name of the language is displayed

---

packages/core/src/data-fetching/api/PrezlyApi.ts
packages/core/src/data-fetching/api/queries.ts
packages/nextjs/src/adapter-nextjs/page-props/home.ts
packages/nextjs/src/adapter-nextjs/page-props/sitemap/getServerSideProps.ts
packages/nextjs/src/adapter-nextjs/page-props/story.ts
packages/nextjs/src/infinite-loading/useInfiniteStoriesLoading.ts

We agreed that fragmenting theme functionality for story pinning was not a good call.
I propose enabling it by default, marking it as deprecated, and removing the option completely with the next major release. Since this property only controls the order of the stories returned, there are no breaking changes or critical changes to functionality.

[CARE-3106] Make story pinning enabled by default

---

packages/nextjs/src/adapters/metadata/lib/utils/mergePageMetadata.ts

The empty `robots: {}` property was overriding the meaningful one defined in the root layout, as Next.js doesn't use deep-merge strategy for metadata props.

[CARE-3749] Fix - Missing `robots` metatag on homepage

---

packages/intl/src/formatting/datetime/lib.ts
packages/react/src/intl/BaseFormattedTime.tsx

`FormattedTime` will now return the full GMT offset and GMT will be replaced by UTC, so the result will be something like this `08:00 AM UTC+01:00`

[CARE-4368] Display UTC offset when formatting time

---

lerna.json
package-lock.json
packages/core/package.json
packages/intl/package.json
packages/nextjs/package.json
packages/nextjs/src/adapters/metadata/lib/utils/mergePageMetadata.ts
packages/react/package.json
packages/ui/package.json

The problem was the merging function using empty object as a default for `undefined` property.
In this case, if you don't provide the `verification` property when calling `generatePageMetadata` function both sides default to `undefined`, producing `verification: {}` result, which does not get omitted by `omitUndefined` helper. Next.js then takes this value and overrides the `verification` property provided from `generateRootMetadata`.
With this fix, all the pages will correctly inherit the `verification` property, unless it's explicitly overwritten.

[CARE-4849] Fix - `verification` metadata property being overwritten

---

packages/nextjs/src/config.ts

This is the same change as in https://github.com/prezly/theme-kit-js/pull/682 but for the older version 7 (still used in Lena, Greta and Marcel themes).

[CARE-4999] Feature - Update CSP header to allow iframing in the app

---

packages/core/src/constants.ts
packages/core/src/galleries.ts

Followup on https://github.com/prezly/theme-nextjs-bea/pull/1192

[CARE-6365] Fix - Add secondary base url for assets that Uploadcare recommends

---

packages/nextjs/src/sentry/common.ts

This is the same fix but for the `7.x` version.

[DEV-13725] Fix - Reduce transactions sample rate to 0.5%

---

packages/core/src/content-delivery/ContentDelivery.ts
packages/intl/src/locales/pickSuportedLocale.ts
packages/nextjs/src/adapters/prezly/cache/redis.ts

We need to be able to search stories based on multiple categories for the BNP Paribas custom theme, so I've changed the `category` parameter to an array of `categories`.

Feature - Allow multiple categories when searching stories
